#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os 
import sys

sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'src_torch'))

from dafne_models.ui.ModelTrainer import main as execute_model_trainer

if __name__=='__main__':
    execute_model_trainer()