[metadata]
name = dafne-models
version = attr: dafne_models.__version__
author = Francesco Santini
author_email = francesco.santini@unibas.ch
description = Deep Learning models module for Dafne
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/dafne-imaging/dafne-models
project_urls =
    Bug Tracker = https://github.com/dafne-imaging/dafne-model/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
    Operating System :: OS Independent

[options]
# before package_dir =
#    = src
package_dir =
    = src_torch
packages = find:
python_requires = >=3.6
install_requires =
    #dafne_dl >= 1.4a2
    dafne_dl-torch_models @ git+https://github.com/GiuseppeTimpano/dafne-dl.git@torch_models
    matplotlib
    monai
include_package_data = True

[options.extras_require]
gui =
    PyQt5

[options.packages.find]
# before where = src
where = src_torch

[options.package_data]
#defne_models = resources/*
dafne_models = models/*

[options.entry_points]
console_scripts =
#    create_model = dafne_models.bin.create_model:main
#    create_model_ui = dafne_models.ui.ModelTrainer:main
    dafne_trainer = dafne_models.ui.ModelTrainer:main